global using ProTechniqueInfrastructure.Core.Utilities.Results;
global using ProTechniqueInfrastructure.Entities.Concrete;
global using ProTechniqueInfrastructure.Business.Abstract;
global using ProTechniqueInfrastructure.DataAccess.Abstract;
global using ProTechniqueInfrastructure.Business.Constants;